# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Verify

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest  # For a list of available runner types, refer to

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore

    - name: Start and check the project
      run: |
        dotnet run --no-build --project LogiTrack\LogiTrack\LogiTrack.csproj &
        sleep 20 
        echo "Application started successfully"
        pkill -f "dotnet"   
